In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


%matplotlib inline

In [24]:
dataset = pd.read_csv('Dane_lab6.csv')
dataset.head(10)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [49]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print (x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [34]:
from sklearn.impute import SimpleImputer

In [36]:
imputer = SimpleImputer(missing_values=np.nan, strategy= 'mean')

In [41]:
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [42]:
from sklearn.preprocessing import LabelEncoder

In [50]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [51]:
le = LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [57]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [61]:
ct = ColumnTransformer(
transformers = [(
    'encoder',
    OneHotEncoder(),
    [0]
)],
remainder='passthrough')

In [62]:
x = np.array(
    ct.fit_transform(x)
)

In [69]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [71]:
from sklearn.model_selection import train_test_split

In [72]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=1
)

In [73]:
print(f'In the TEST set there are {x_train.shape[0]} cases')

In the TEST set there are 8 cases


In [74]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [75]:
x_train

array([[0.0, 0.0, 1.0, nan, 52000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [76]:
print(f'In the TEST set there are {y_train.shape[0]} cases')

In the TEST set there are 8 cases


In [77]:
y_test

array([0, 1])

In [78]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [79]:
from sklearn.preprocessing import StandardScaler

In [80]:
sc = StandardScaler()

In [81]:
x_train

array([[0.0, 0.0, 1.0, nan, 52000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [82]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [87]:
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

In [89]:
x_train

array([[0.0, 0.0, 1.0, nan, -1.0182239953527132],
       [0.0, 1.0, 0.0, -0.03891021128204815, nan],
       [1.0, 0.0, 0.0, 0.5058327466666259, 0.5834766714942514],
       [0.0, 0.0, 1.0, -0.31128169025638514, -0.2974586952715791],
       [0.0, 0.0, 1.0, -1.8093248246152385, -1.3385641287221062],
       [1.0, 0.0, 0.0, 1.0505757046152997, 1.1440719048906889],
       [0.0, 1.0, 0.0, 1.3229471835896367, 1.4644120382600818],
       [1.0, 0.0, 0.0, -0.7198389087178906, -0.5377137952986237]],
      dtype=object)

In [90]:
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [91]:
x_test

array([[0.0, 1.0, 0.0, -1.400767606153733, -0.8580539286680166],
       [1.0, 0.0, 0.0, -0.44746742974355364, 0.18305150478251025]],
      dtype=object)